rules:
  color-no-invalid-hex: true
  declaration-no-important: true
  shorthand-property-no-redundant-values: true
  function-url-no-scheme-relative: true
  no-extra-semicolons: true
  no-invalid-double-slash-comments: true
  no-duplicate-selectors: true
  no-duplicate-at-import-rules: true
  no-descending-specificity: true
  comment-no-empty: true
  at-rule-no-unknown: true
  media-feature-name-no-unknown: true
  selector-type-no-unknown: true
  selector-pseudo-element-no-unknown: true
  selector-pseudo-class-no-unknown: true
  block-no-empty: true
  declaration-block-no-duplicate-properties: true
  declaration-block-no-shorthand-property-overrides: true
  property-no-unknown: true
  unit-no-unknown: true
  string-no-newline: true
  color-hex-case: "lower"
  color-hex-length: "short"
  font-family-name-quotes: "always-unless-keyword"
  font-weight-notation:
  	- "numeric"
  	- ignore: "relative"
  indentation:
  	- "tab"
  	- indentClosingBrace: false
  max-empty-lines: 1
  no-eol-whitespace: true
  no-missing-end-of-source-newline: true
  no-empty-first-line: true
