language: php
php:
- '5.6'
- '7.0'
- '7.1'
- nightly
env:
  matrix:
  - DB=mysql
  global:
  - secure: Q1Ebv2paWspYxTJtVWMx8KswWPJVeY8wXNrYqelgYNyxCjJVyunzMmtVKOBmNMDePDD1oLhrCtlZ8kUsx3tIWRI8jSWuOfyRbnjoLtFrNLY0kPkKrx2Tg2PmIH/lbmz4IBFgJ/3XJHz/9pY+ouhkZ+Tkvf1Vh4xmtdLk0rkj8STwO30r7j8pe8/YdNURuJ1i6UiCn/Na3vbocfXLlrGCCLk44be7Wvd9EBzfUB3Rocl1AJ71sP0VW7h5fWKq8UqvGip/rEvPAe9UKLcTe1DG8eJ5iJmcQ0Wh0ljqKYfVkPS+qiyDm4/iAxfZoAP0LszLZBw2xOoBoo4U2llQng3BZrXZP/k2Fnd/LPXWHi6vp0B0tQynZ4qrl62pbvvYE0LbWdAfi8R/IdzCeBQmxBAA83vCTkCG1TCnFc/sNURVght0SaRSxHXoDadyWfxDmxAFswy1LLSugCP4XaBhlBhrl9F6ezD5ZC4Qv7/YsdQ9sfr021LU4gtYgFf8VRLDknEb4pamC2iBAojAVi71uakBy8qcV4d4SkgdT39m4SVJ3QCqihhw+TAmB2wgzvjrFNPLHDTla4Y1PHPH1K67979dSZOwV43FwN8gbiOSjTfk6JlstmdwHpgHJ3h1ohwQSr8MJ0ZgCoZrKHqgrqeLaXj/6xh9NbSprNSxUaDpAc/aAPc=
  - secure: QmP8JvySF1oHvmLHg7MUDbOhz8XqovyUapoaFteGXVz/tqz1exqJ4vZ3Xe/Wee6rIQVt5Y8deSGA3Cs2J3uUzZDWCewOcie7I1yF81hTgLO7bqpvxwssu66JWKxrZI1K+tIPemunhXPtjbg9fidQ5CXrUO69R+HVSwiKdGtomHONVUOnZ6YtZm+8qRBBQtwBmRkaSRop0nj2mMbxAjv3BlLmPBmxlDx4x/DPmSdDqS06CKv3MnwetETM3C4drllDogUkgM+cMctRObi3ptNwY43teRsQ34X2G1hvG1ZY3LPvORJL+e2kqfismVAQGrStVEo0R7ND15mo4XDZ0UU/dQOxKV3cGKnNPIQkM7oNVdbfTL9HlIQX4R5hknai46vBMEjMivWvIWbkj8apI6fO57WOKqYZE0i23vNH/sliEP0j51/bP/1GE+FFE6YLfjaJgFAau5Y04mWPC66CeVTjPVL+VeDsyl/ACUbGzcDOIxM9N7xd6DxOr8bz6R1cZesY2v+ts65irPy9rG61MRXt3uQ2/ALsEbX3f980Fy/4czM9lpOAK0RfRkpcUU369qFMj82SEUsQMc588mU8iRC380o8qp6lzj2mWNCz8KzB9sJXTXldiLfKSzSo2K0N7XGpo7DcctXNXijeiUok39C7oagI2o7TEw/32DKYBdBUPVc=
matrix:
  allow_failures:
  - php: nightly
before_script:
- phpenv config-rm xdebug.ini
script:
- phpunit --configuration travisci-phpunit.xml
before_deploy:
- cd ..
- zip -r plg_system_lesstemplatecompanion.zip plg_system_lesstemplatecompanion/src -x \*.git\* *.gitattributes*
deploy:
  provider: releases
  file:
  - plg_system_lesstemplatecompanion.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: TNakyqlvRXLGthkTdh4Q1s/Cx5bDoof2MX7Pv+4OwayYRMu5lRAqNoAU5SX/hZJ4KljaKX2Umqa+08wiSioWh0TF8k70Q9p3Y0vjUeYGuQegmn+Olp/xEMZbMExhJKTC244V77p0wvjKcqdkw//ahkF7se9EPd+EsA4nT0FE1JyrZgEfmz4MOpXDJJWeM7skZXk3z4c3RC7oP7IHNSir/H10VXZeJeMrei/Aesj2UgIoWoVDjXFD9ySOUbqAv9XqYHoK3kXOz/oP+bZKbMXu+4i1PKKQFggdCQNulyMmlgbEkFz7w2jGrhgwFngMqhV5PNUizHS/A+FJlNLG/EKYWeprcNxSJYkLzKWS1+tqyYgHJaser7Mbey5A7VqoeRWyTX8ajAKZW5T+TQsfTzhHeiwX0yzx1gGwmb71K/7FBfQ3Rtjh7NUh1jJNwbNaBCKqnKxHgGnA02p5k1I6wlgSJ0KEhu7oi6NKi65e21xaL2fzo65SB7YgpVFtiYJeWSX8j8y9TFv5Hv2G++IHgGfwRLbyer9nQ0vPn9M+QrTgX8MRercRdxLbziH1Uy1cZh2O9iT3VE2VQGam5wRQ8GcN6XPzbuKQ0eAx7tgGFA8koByt8IzPIUAe7iDe8mS8grbX1qwqZ901l9CSp/CH43GE9hRprwfrht846p7iqte1MD0=
after_deploy: curl -T plg_system_lesstemplatecompanion/plg_system_lesstemplatecompanion_updates.xml
  -u $FTP_USER:$FTP_PASSWORD ftp://gilebabe.webhosting.be/
