language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- '7.3'
- '7.4'
- nightly
env:
  jobs:
  - DB=mysql
jobs:
  allow_failures:
  - php: nightly
before_script:
- composer install
- cd ..
- git clone https://github.com/joomla/joomla-cms joomla-cms
script:
- plg_system_templatecompanion/vendor/bin/phpunit --configuration plg_system_templatecompanion/travisci-phpunit.xml --include-path ./plg_system_templatecompanion/vendor/bin/phpunit
after_script:
- cd plg_system_templatecompanion/
- php vendor/bin/codacycoverage clover tmp/coverage.xml
before_deploy:
- zip -r plg_system_templatecompanion.zip plg_system_templatecompanion/src -x \*.git\* *.gitattributes*
deploy:
  provider: releases
  edge: true
  file:
  - plg_system_templatecompanion.zip
  on:
    tags: true
  api_key: $GITHUB_TOKEN
after_deploy:
  - curl -T plg_system_templatecompanion/plg_system_templatecompanion_updates.xml -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
