language: php
php:
- '5.6'
- '7.0'
- '7.1'
- '7.2'
- nightly
env:
  matrix:
  - DB=mysql
  global:
  - secure: K1iPTfCnPT1JHAkozJ7o/XN0m9IzBW1dYiC/AQfjxdKWhRgv8/6W0hq9ANWR0YZ6GUifIdzsB6cT8wj25J2S1uVyiN48BzXHA8tfmHS9xcvLlCY4o/dEU+0JTPlY30Q/Ft2FF7ZzGcJY5xfeiYpYBh+4yaujLmWMj9hCzTGfYYoFyp8PuMsg6peOsfMWbD+gTjtR23IAu8NenRYHYButB7IxnEU0YleIei2bH4xPRVYhA1dZ25/GHWYBDXVRYmCOcm+KGLrfxiqkqVCpDIQBmcjapwOaG+kFe3G4730MrrzDhpYbBC6tb/2oqqqP3/skhlxn/i4SqWM/4X6hUsmYjkQxcUtVQMSVEaGDwP780TssDEQ4G1bf2hudPQ1ebWpkWOrtIoJuai4SInfSSR6NqbsVCCZSzrG7qZFlfSjO9cXCr2mA98V6xD1odUveZ5wTgf1dINi9XEyZ6PsU9R+XclZCStTcozRItAPsxIjictteGJRXZ/RmezPlNMUTQ7gzo1KU8jpCCVuVBeHReBgefbfQ/VmoDxdhavpaq6ZKbSgL8spr06C9noYk9as8ut3MsMiYdJPrxh8OrTLACdRhqpFiNaoRBXmYbRLTSc6ygrXOS1O1WmYvn3AH/E8uQ7cVhGWELZzui6i9xXFZGn4K6Z9HFMyborPd9K2jMprO72E=
matrix:
  allow_failures:
  - php: nightly
before_script:
- composer install
- cd ..
- git clone https://github.com/joomla/joomla-cms joomla-cms
script:
- plg_system_lesstemplatecompanion/vendor/bin/phpunit --configuration plg_system_lesstemplatecompanion/travisci-phpunit.xml --include-path ./plg_system_lesstemplatecompanion/vendor/bin/phpunit
after_script:
- cd plg_system_lesstemplatecompanion/
- php vendor/bin/codacycoverage clover tmp/coverage.xml
before_deploy:
- zip -r plg_system_lesstemplatecompanion.zip plg_system_lesstemplatecompanion/src -x \*.git\* *.gitattributes*
deploy:
  provider: releases
  file:
  - plg_system_lesstemplatecompanion.zip
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: TNakyqlvRXLGthkTdh4Q1s/Cx5bDoof2MX7Pv+4OwayYRMu5lRAqNoAU5SX/hZJ4KljaKX2Umqa+08wiSioWh0TF8k70Q9p3Y0vjUeYGuQegmn+Olp/xEMZbMExhJKTC244V77p0wvjKcqdkw//ahkF7se9EPd+EsA4nT0FE1JyrZgEfmz4MOpXDJJWeM7skZXk3z4c3RC7oP7IHNSir/H10VXZeJeMrei/Aesj2UgIoWoVDjXFD9ySOUbqAv9XqYHoK3kXOz/oP+bZKbMXu+4i1PKKQFggdCQNulyMmlgbEkFz7w2jGrhgwFngMqhV5PNUizHS/A+FJlNLG/EKYWeprcNxSJYkLzKWS1+tqyYgHJaser7Mbey5A7VqoeRWyTX8ajAKZW5T+TQsfTzhHeiwX0yzx1gGwmb71K/7FBfQ3Rtjh7NUh1jJNwbNaBCKqnKxHgGnA02p5k1I6wlgSJ0KEhu7oi6NKi65e21xaL2fzo65SB7YgpVFtiYJeWSX8j8y9TFv5Hv2G++IHgGfwRLbyer9nQ0vPn9M+QrTgX8MRercRdxLbziH1Uy1cZh2O9iT3VE2VQGam5wRQ8GcN6XPzbuKQ0eAx7tgGFA8koByt8IzPIUAe7iDe8mS8grbX1qwqZ901l9CSp/CH43GE9hRprwfrht846p7iqte1MD0=
after_deploy: curl -T plg_system_lesstemplatecompanion/plg_system_lesstemplatecompanion_updates.xml
  -u $FTP_USER:$FTP_PASSWORD $FTP_SERVER
